### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused when used with Vagrant

### ISSUE THREAD

**Issue by tiagoleal25** [Chapabu/codeception-module-drupal#1]
Hi @Chapabu,

i'm trying to use this module on codeception to test my drupal website.
On acceptance.suite.yml i can't define configure the root folder. I'm using vagrant environment on my project.  When i execute my test, i had always this message:

SQLSTATE[HY000] [2002] Connection refused codeception

What do you think where is the problem?

Best regards,
Tiago

**Comment by Chapabu** [comment]
I've not seen this error before :/ are you running your tests by SSH'ing into your Vagrant box or on your host machine? It might be useful for you to post your entire acceptance.yml file if that's OK?

**Comment by tiagoleal25** [comment]
Hi @Chapabu, first of all, thank you for answering.
The question is related with the path of the root folder of drupal site. I'm running the tests out of vagrant box. 

\Codeception\Module\Drupal7\Drupal7:
            root: '/Users/myuser/Sites/mywebsite/www'
            relative: no
![captura de ecra 2015-05-4 as 15 10 00](https://cloud.githubusercontent.com/assets/12188665/7454861/adafad7a-f26f-11e4-883c-026e731d3427.png)

**Comment by Chapabu** [comment]
No problem :) 

I'd wager that you're running Drupal inside a Vagrant box with localhost database settings? When you run your tests, Drupal is bootstrapping with the settings in your current settings.php file. If you run your tests outside of your Vagrant box then the module will be using the currently active credentials, which may not be correct on the host machine. 

Can you try SSH'ing into your Vagrant box and running your tests?

**Comment by tiagoleal25** [comment]
Yes, my idea is to run the tests out of the Vagrant box and i'm using a localhost database settings. Running the tests on the Vagrant box, i get some errors. There is a screenshot.

![captura de ecra 2015-05-5 as 10 19 43](https://cloud.githubusercontent.com/assets/12188665/7469906/63dfa852-f310-11e4-8dd4-50fcc8199ec3.png)

**Comment by tiagoleal25** [comment]
@Chapabu do you know why this happens?

**Comment by Chapabu** [comment]
Sorry for the delay with this one, I've managed to get myself massively busy!

I've so far not been able to replicate the issue locally, but I'll try and get a Vagrant box running at the weekend and see if I can replicate it.

**Comment by tiagoleal25** [comment]
Ok, thanks for the preoccupation. 
I will wait for your feedback...

**Comment by tiagoleal25** [comment]
If that helps you, maybe, i think that the problem is related with some conflict with a module that i'm using on my website. Please, let me know.

**Comment by Chapabu** [comment]
I had a quick go at this and couldn't replicate reliably. I'm happy to re-open should someone be able to provide a full setup for replication.
